---

- name: Create mongodb user
  user: name={{ mongodb_user }} createhome=no

- name: Ensure dbpath directory
  file: path={{ mongodb_storage_dbpath }} state=directory owner={{ mongodb_user }} recurse=yes

- name: Download automation agent rpm
  get_url: url={{ mongodb_mms_agent_pkg }} dest={{ mongodb_storage_dbpath }}/mms-agent.rpm
  register: mongodb_mms_agent_loaded

- name: Install automation agent
  yum: name={{ mongodb_storage_dbpath }}/mms-agent.rpm state=present
  when: mongodb_mms_agent_loaded.changed

- name: Configure automation agent
  template: src=automation-agent.config.j2 dest={{ mongodb_storage_dbpath }}/automation-agent.config
  notify: mongodb-mms-automation-agent restart

- name: Ensure automation agent is started
  service: name=mongodb-mms-automation-agent state=started enabled=yes

