---

- name: Create automation configuration
  template: src=/templates/opsmgr_api_replset.js dest={{ mongodb_storage_dbpath }}/opsmgr_api_replset mode=0644

- name: Send configuration to Ops Manager
  command: curl -u "{{ mongodb_opsmgr_api_user }}:{{ mongodb_opsmgr_api_key }}" -H "Content-Type: application/json" "http://{{ mongodb_mms_base_url }}/api/public/v1.0/groups/{{ mongodb_mms_group_id }}/automationConfig" --digest -i -X PUT --data @{{ mongodb_storage_dbpath }}/opsmgr_api_replset
